services:
  www:
    image: kugland/darkhttpd:latest
    container_name: cloud_site_thekhanj_ir
    volumes:
      - "/var/www/thekhanj.ir:/www:ro"
    ports:
      - "3085:80"
    restart: always
    networks:
      - cloud

networks:
  cloud:
    external: true
