name: Deploy to Server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ssh key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run command on server
        run: ssh-add -l
        # run: ssh root@ir2.hollalujah.ir "cd /var/www/html/cv && git pull && make && systemctl restart nginx"
